12-20 19:46:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PASSWORD" not found; SQL statement:
insert into User (username, password) VALUES (?,?) [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.Table.getColumn(Table.java:624)
	at org.h2.command.Parser.parseColumn(Parser.java:815)
	at org.h2.command.Parser.parseColumnList(Parser.java:800)
	at org.h2.command.Parser.parseInsert(Parser.java:993)
	at org.h2.command.Parser.parsePrepared(Parser.java:385)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertUser(JdbcUserStore.java:42)
	at com.thn.netty.chat.server.UserManager.createUser(UserManager.java:37)
	at com.thn.netty.chat.server.ServerLogicHandler.processCreateAccount(ServerLogicHandler.java:82)
	at com.thn.netty.chat.server.ServerLogicHandler.channelRead0(ServerLogicHandler.java:52)
	at com.thn.netty.chat.server.ServerLogicHandler.channelRead0(ServerLogicHandler.java:1)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:724)
12-20 19:47:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PASSWORD" not found; SQL statement:
insert into User (username, password) VALUES (?,?) [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.Table.getColumn(Table.java:624)
	at org.h2.command.Parser.parseColumn(Parser.java:815)
	at org.h2.command.Parser.parseColumnList(Parser.java:800)
	at org.h2.command.Parser.parseInsert(Parser.java:993)
	at org.h2.command.Parser.parsePrepared(Parser.java:385)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertUser(JdbcUserStore.java:42)
	at com.thn.netty.chat.server.UserManager.createUser(UserManager.java:37)
	at com.thn.netty.chat.server.ServerLogicHandler.processCreateAccount(ServerLogicHandler.java:82)
	at com.thn.netty.chat.server.ServerLogicHandler.channelRead0(ServerLogicHandler.java:52)
	at com.thn.netty.chat.server.ServerLogicHandler.channelRead0(ServerLogicHandler.java:1)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:103)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:108)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:153)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:338)
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
	at java.lang.Thread.run(Thread.java:724)
12-26 20:28:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement " ALTER TABLE CONTACT ADD CONSTRAINT PRIMARY[*] KEY (USERID, CONTACTID);ALTER TABLE CONTACT ADD CONSTRAINT FOREIGN KEY (USERID) REFERENCES USER(USERID); "; expected "identifier"; SQL statement:
 ALTER TABLE Contact ADD CONSTRAINT PRIMARY KEY (userid, contactid);ALTER TABLE Contact ADD CONSTRAINT FOREIGN KEY (userid) REFERENCES User(userId); [42001-174]
12-26 20:30:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement " ALTER TABLE CONTACT ADD CONSTRAINT PRIMARY[*] KEY (USERID, CONTACTID); "; expected "identifier"; SQL statement:
 ALTER TABLE Contact ADD CONSTRAINT PRIMARY KEY (userid, contactid); [42001-174]
12-26 20:31:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "USERID" must not be nullable; SQL statement:
create table Contact (userid int, contactid int); ALTER TABLE Contact ADD PRIMARY KEY (userid, contactid); [90023-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.RegularTable.addIndex(RegularTable.java:203)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:131)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:70)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:37)
	at org.h2.command.CommandList.update(CommandList.java:44)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at com.thn.netty.chat.server.store.JdbcUserStore.createTables(JdbcUserStore.java:23)
	at com.thn.netty.chat.server.store.JdbcUserStore.<init>(JdbcUserStore.java:140)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:148)
12-26 20:40:06 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into user values ('Bob', 'mypass') [21002-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.message.DbException.get(DbException.java:137)
	at org.h2.command.dml.Insert.prepare(Insert.java:233)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:371)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:642)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsProvider.readData(SQLEditor.java:1116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:122)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
12-26 20:44:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE CONTACT ADD CONSTRAINT FOREIGN KEY (USERID) REFERENCES[*] USER(USERID); "; SQL statement:
ALTER TABLE Contact ADD CONSTRAINT FOREIGN KEY (userid) REFERENCES User(userId); [42000-174]
12-26 20:45:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO USER (USERNAME, PASSWORD) VALUES ('Alice', 'mypass')
INSERT[*] INTO CONTACT VALUES(1, 2) "; SQL statement:
insert into user (username, password) values ('Alice', 'mypass')
insert into contact values(1, 2) [42000-173]
12-28 10:13:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Attempt to define a second primary key; SQL statement:
 ALTER TABLE Contact ADD PRIMARY KEY (userid, contactid);ALTER TABLE Contact ADD FOREIGN KEY (userid) REFERENCES User(userId);ALTER TABLE Contact ADD FOREIGN KEY (contactid) REFERENCES User(userId); [90017-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:70)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:37)
	at org.h2.command.CommandList.update(CommandList.java:44)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at com.thn.netty.chat.server.store.JdbcUserStore.createTables(JdbcUserStore.java:29)
	at com.thn.netty.chat.server.store.JdbcUserStore.<init>(JdbcUserStore.java:207)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:222)
12-28 10:13:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PENDINGCONTACT" already exists; SQL statement:
create table PendingContact (userid int NOT NULL, contactid int NOT NULL); ALTER TABLE PendingContact ADD PRIMARY KEY (userid, contactid);ALTER TABLE PendingContact ADD FOREIGN KEY (userid) REFERENCES User(userId);ALTER TABLE PendingContact ADD FOREIGN KEY (contactid) REFERENCES User(userId); [42101-174]
01-01 12:53:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into contact values(?,?) [21002-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:233)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertContact(JdbcUserStore.java:232)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistContacts(JdbcUserStore.java:87)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistUser(JdbcUserStore.java:74)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:366)
01-01 12:53:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into contact values(?,?) [21002-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:233)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertContact(JdbcUserStore.java:232)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistContacts(JdbcUserStore.java:87)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistUser(JdbcUserStore.java:74)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:366)
01-01 13:12:37 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into contact values(?,?) [21002-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:233)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertContact(JdbcUserStore.java:232)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistContacts(JdbcUserStore.java:87)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistUser(JdbcUserStore.java:74)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:366)
01-02 22:41:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "C.PENDING" not found; SQL statement:
select u.userid, u.username, u.password, c.pending from user u, contact c where c.contactid = u.userid and c.userid = ? [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Select.prepare(Select.java:810)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.getContacts(JdbcUserStore.java:313)
	at com.thn.netty.chat.server.store.JdbcUserStore.getUserByName(JdbcUserStore.java:236)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:396)
01-02 22:42:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PENDING" not found; SQL statement:
update contact set pending = ? where userid = ? and contactid = ? [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.Table.getColumn(Table.java:624)
	at org.h2.command.Parser.readTableColumn(Parser.java:668)
	at org.h2.command.Parser.parseUpdate(Parser.java:702)
	at org.h2.command.Parser.parsePrepared(Parser.java:437)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.updateContact(JdbcUserStore.java:286)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistContacts(JdbcUserStore.java:107)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistUser(JdbcUserStore.java:77)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:406)
01-02 22:42:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "PENDING" not found; SQL statement:
update contact set pending = ? where userid = ? and contactid = ? [42122-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.table.Table.getColumn(Table.java:624)
	at org.h2.command.Parser.readTableColumn(Parser.java:668)
	at org.h2.command.Parser.parseUpdate(Parser.java:702)
	at org.h2.command.Parser.parsePrepared(Parser.java:437)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.parse(Parser.java:261)
	at org.h2.command.Parser.prepareCommand(Parser.java:226)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.updateContact(JdbcUserStore.java:286)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistContacts(JdbcUserStore.java:107)
	at com.thn.netty.chat.server.store.JdbcUserStore.persistUser(JdbcUserStore.java:77)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:406)
01-06 15:37:20 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "C.PENDING" not found; SQL statement:
select u.userid, u.username, u.PASSWORD, c.PENDING from user u, contact c where c.contactid = u.userid and c.userid = 1 [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Select.prepare(Select.java:808)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:371)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:642)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsProvider.readData(SQLEditor.java:1116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:122)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
01-06 15:37:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "C.PENDING" not found; SQL statement:
select u.userid, u.username, u.PASSWORD, c.PENDING from user u, contact c where c.contactid = u.userid and c.userid = 1 [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Select.prepare(Select.java:808)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:371)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:642)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsProvider.readData(SQLEditor.java:1116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:122)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
01-06 20:44:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT U.USERID, U.USERNAME, U.PASSWORD, C.STATE FROM USER U, CONTACT C WHERE C.USERID = U.USERID AND C.CONTACTID = ? AND C.STATE[*] == ? "; SQL statement:
select u.userid, u.username, u.PASSWORD, c.STATE from user u, contact c where c.userid = u.userid and c.contactid = ? and c.state == ? [42000-174]
01-07 09:57:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "hello" not found; SQL statement:
insert into message values(1,2,"hello") [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:238)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:371)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:642)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsProvider.readData(SQLEditor.java:1116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:122)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
01-07 09:57:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "hello" not found; SQL statement:
insert into message values(1,2,"hello") [42122-173]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:331)
	at org.h2.message.DbException.get(DbException.java:171)
	at org.h2.message.DbException.get(DbException.java:148)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:238)
	at org.h2.command.Parser.prepareCommand(Parser.java:219)
	at org.h2.engine.Session.prepareLocal(Session.java:428)
	at org.h2.engine.Session.prepareCommand(Session.java:377)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:168)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:340)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:134)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:371)
	at org.jkiss.dbeaver.runtime.sql.SQLQueryJob.extractData(SQLQueryJob.java:642)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsProvider.readData(SQLEditor.java:1116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataPumpJob.run(ResultSetDataPumpJob.java:122)
	at org.jkiss.dbeaver.runtime.AbstractJob.run(AbstractJob.java:91)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
01-07 10:05:59 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO MESSAGE VALUES(1,2,'hello')
SELECT[*] M.MESSAGE, U.USERNAME FROM MESSAGE M, USER U WHERE RECIPIENTID = 2 AND M.RECIPIENTID = U.USERID "; SQL statement:
insert into message values(1,2,'hello')
select m.message, u.username from message m, user u where recipientid = 2 and m.recipientid = u.userid [42000-173]
01-07 10:06:06 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO MESSAGE VALUES(1,2,'hello')
SELECT[*] M.MESSAGE, U.USERNAME FROM MESSAGE M, USER U WHERE RECIPIENTID = 2 AND M.RECIPIENTID = U.USERID "; SQL statement:
insert into message values(1,2,'hello')
select m.message, u.username from message m, user u where recipientid = 2 and m.recipientid = u.userid [42000-173]
01-08 09:59:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Attempt to define a second primary key; SQL statement:
ALTER TABLE Message ADD PRIMARY KEY (senderid, recipientid);ALTER TABLE Message ADD FOREIGN KEY (senderid) REFERENCES User(userId);ALTER TABLE Message ADD FOREIGN KEY (recipientid) REFERENCES User(userId); [90017-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:110)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:70)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.command.CommandList.update(CommandList.java:43)
	at org.h2.command.CommandList.executeRemaining(CommandList.java:37)
	at org.h2.command.CommandList.update(CommandList.java:44)
	at org.h2.command.Command.executeUpdate(Command.java:253)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:181)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:156)
	at com.thn.netty.chat.server.store.JdbcUserStore.createTables(JdbcUserStore.java:39)
	at com.thn.netty.chat.server.store.JdbcUserStore.<init>(JdbcUserStore.java:446)
	at com.thn.netty.chat.server.store.JdbcUserStore.main(JdbcUserStore.java:462)
01-08 10:00:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into message values(?,?,?) [21002-174]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.h2.message.DbException.get(DbException.java:149)
	at org.h2.message.DbException.get(DbException.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:233)
	at org.h2.command.Parser.prepareCommand(Parser.java:231)
	at org.h2.engine.Session.prepareLocal(Session.java:437)
	at org.h2.engine.Session.prepareCommand(Session.java:380)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1138)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:70)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:267)
	at com.thn.netty.chat.server.store.JdbcUserStore.insertMessage(JdbcUserStore.java:386)
	at com.thn.netty.chat.server.UserManager.insertMessage(UserManager.java:85)
	at com.thn.netty.chat.server.ServerLogicHandler$6.run(ServerLogicHandler.java:361)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
